export const BASE_PATH = 'http://localhost:3000'
export const SITE_NAME = 'The Sapphire Clinics'
export const baseURL='/'
export const imgblurDataURL='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mPsqQcAAZ0BDTSBuAQAAAAASUVORK5CYII='
export const HOME_OG_IMAGE_URL ='/images/sclogo.png'
